### PR TITLE
Speed up tests by parallelization using pytest-split 

### PR DESCRIPTION
**Pull request by kamronald**
## Summary

Major changes:

Add pytest-split as a dependency during testing to parallelize the test suite

## Checklist

- [ ] All existing tests pass.
- [ ] Tests have been added for any new features/fixes.
- [ ] Docstrings have been added in the [Google docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).

### CODE REVIEW

**Comment by kamronald** [comment]
Hey @lbluque and @qchempku2017, are either of you able to access the branch protection rules? Currently the test(3.9) checks on the Github actions workflow is not running as expected. Just says "Expected - Waiting for status to be reported"

I'm wondering if I can remove that test somehow.

**Comment by qchempku2017** [comment]
> Hey @lbluque and @qchempku2017, are either of you able to access the branch protection rules? Currently the test(3.9) checks on the Github actions workflow is not running as expected. Just says "Expected - Waiting for status to be reported"
> 
> I'm wondering if I can remove that test somehow, but am not able to manage branch protection rules.

@kamronald Hi Ronald I‘m really eager to help, but I really have no idea about where to start from. @lbluque Would you mind having a look at the issue Ronald mentioned and teach us how to fix it?

**Comment by kamronald** [comment]
So the issue I have is discussed here: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule
I am not able to see the branch protection rules, but perhaps @lbluque or @qchempku2017 you guys can?

**Comment by lbluque** [comment]
Hi @kamronald, I made you Admin, can you check if you can see branch protection rules now?

**Comment by kamronald** [comment]
Yes @lbluque can see them now and made some changes, thanks!

**Pull request merged**
