### PR TITLE
Fix cluster unit tests

### PR DESCRIPTION
**Pull request by lbluque**
## Summary
- fix failing cluster unit tests

## Checklist

- [ ] All existing tests pass.
- [X] Tests have been added for any new features/fixes.
- [X] Docstrings have been added in the [Google docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).

Tip: Install `pre-commit` hooks to auto-check types and linting before every commit:

```sh
pip install -U pre-commit
pre-commit install
```

### CODE REVIEW

**Review by kamronald — APPROVED** [review]

**Comment by kamronald** [comment]
I'm not sure why the tests are still failing when I try to merge the PR - specifically the process is killed at test_objectives.py. Checked that this test is able to run locally, although some other ones are not passing

**Comment by lbluque** [comment]
Hmm I can't figure out why test_solver fails. I'll investigate when I get a chance.

Which tests were failing locally?

**Comment by kamronald** [comment]
The ones involving the SCIP solver, apparently I just don't have it installed properly

**Comment by kamronald** [comment]
Seems like the error with test_solver is that the virtual machine runs out of memory. I'm not sure why they only started to fail recently. I asked the Github team and they say the specs for the machines are 2-core CPU, 7 GB of RAM memory, and 14 GB of SSD disk space. Maybe we need to cut down the memory usage in the tests somehow?

**Comment by qchempku2017** [comment]
Hi guys, this issue might originate from a mismatch of pyscipopt and scip version. In the test.yml workflow, we use scip=8.0.0 as the default binary [version](https://github.com/lbluque/smol/blob/3872e823de438c9ddd353b3073cae5ee92e941d3/.github/workflows/test.yml#L4)
 while in pyproject.toml, we specify pyscipopt to use the latest [version.](https://github.com/lbluque/smol/blob/3872e823de438c9ddd353b3073cae5ee92e941d3/pyproject.toml#L62)

This might have caused some conflict. I will try running all test suites with either the latest scip=9.1 with pyscipopt=5.1.1, or scip=8.0 with pyscipopt=4.4.0.

**Comment by qchempku2017** [comment]
Due to the wretched **you-know-what policy** in China I had to use some special technique to access github, and my service provider only seems to support pulling from github, not pushing. I have tried pushing multiple times but I'm unable to. I will fix and run the codes locally and I may need your help to push the code and fix the remote testing issue. I appreciate your help.

**Comment by qchempku2017** [comment]
Just checked the local memory consumption. Test objective.py could use up to 10GB of memory. I'll think about reducing the size of the test case.

**Comment by qchempku2017** [comment]
> Seems like the error with test_solver is that the virtual machine runs out of memory. I'm not sure why they only started to fail recently. I asked the Github team and they say the specs for the machines are 2-core CPU, 7 GB of RAM memory, and 14 GB of SSD disk space. Maybe we need to cut down the memory usage in the tests somehow?

Ahh finally able to fix my network issue (just need to turn on the tunnel mode when using SSR). @kamronald @lbluque please check the following [PR](https://github.com/lbluque/smol/pull/67).

Here I have managed to set the correct pyscipopt version in setup.py [test] section, and I have reduced the test size such that the maximum mem usage will be less that 4.5GB.

@lbluque Please approve this PR on your fork. @kamronald please test it out after Luis merges into his fork.

**Comment by kamronald** [comment]
> > Seems like the error with test_solver is that the virtual machine runs out of memory. I'm not sure why they only started to fail recently. I asked the Github team and they say the specs for the machines are 2-core CPU, 7 GB of RAM memory, and 14 GB of SSD disk space. Maybe we need to cut down the memory usage in the tests somehow?
> 
> Ahh finally able to fix my network issue (just need to turn on the tunnel mode when using SSR). @kamronald @lbluque please check the following [PR](https://github.com/lbluque/smol/pull/67).
> 
> Here I have managed to set the correct pyscipopt version in setup.py [test] section, and I have reduced the test size such that the maximum mem usage will be less that 4.5GB.
> 
> @lbluque Please approve this PR on your fork. @kamronald please test it out after Luis merges into his fork.

Thank you very much @qchempku2017! I'll try it out

**Pull request merged**
